Word_list=["PYTHON","HELLO","WORLD","INFORMATICS","INFORMATION","TECHNOLOGY","SEVEN",
            "ELEPHANT","AMERICA","FOOTBALL","CRICKET","HANGMAN","JORDAN","MAHELA","RICE",
            "INSTITUTE","CONSOLE","BASKETBALL","COMPLICATED","GHOST"]